### ISSUE TITLE
The OutputPath property is not set for project 'MovieReviewStarterKit.csproj'

### ISSUE THREAD

**Issue by pappasa** [rahulsahay19/MovieReviewStarterKit#2]
When I try to rebuild the solution, I get the following error in the Output window:

1>------ Skipped Rebuild All: Project: MovieReviewStarterKit, Configuration: Debug x86 ------
1>Project not selected to build for this solution configuration 
========== Rebuild All: 0 succeeded, 0 failed, 1 skipped ==========

When I try to rebuild the project, I get the following error in the Output window:

1>------ Rebuild All started: Project: MovieReviewStarterKit, Configuration: Debug x86 ------
1>C:\Program Files\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(724,5): error : The OutputPath property is not set for project 'MovieReviewStarterKit.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x86'.  This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

![moviereviewstarterkit1](https://cloud.githubusercontent.com/assets/23055341/22543549/a107ed2c-e939-11e6-9807-bdec64d9159b.jpg)

Can you provide a fix for this?

**Comment by rahulsahay19** [comment]
Hi,

What is the Visual Studio Version, you are using here?

Thanks,
Rahul Sahay

**Comment by pappasa** [comment]
I am using VS2017 RC.

![visualstudio2017_1](https://cloud.githubusercontent.com/assets/23055341/22551350/28ffe842-e95d-11e6-8b47-16e102fb04c1.jpg)

**Comment by rahulsahay19** [comment]
Screenshot, which you have sent is of VS-2015. I can also in Recent projects, that is there. This project is not meant for 2015. Its for 2017. I will put this in readme. Since, this is based on LTS(long term support) where .csproj type system is there; hence it will work there.

**Comment by pappasa** [comment]
I have installed this from vs_professional_ENU__1838067779.1463047052.exe which is VS2017 RC. As I understand, because it is still RC (Release Candidate) it displays Visual Studio 2015.

**Comment by rahulsahay19** [comment]
Nope, its not like that I have both versions installed 2015 and 2017 RC. 2017 RC won't display 2015. what you are showing me same version, I have of 2015 with update 3, that is meant for project.json which is current version of DotNet.Core not LTS version.
